name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "npm"

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/out"
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Clean SSH Key
        run: |
          rm -rf ~/.ssh/private.key
          ssh-keygen -f ~/.ssh/known_hosts -R ${{ secrets.REMOTE_HOST }}




  
